hyperledger-identus/apollo

.releaserc.yml
.scripts/updatePackage.swift

Checksum is not being updated on release this is to try and fix it

fix: checksum correctly updated

---

.releaserc.yml
.scripts/TemplatePackage.swift

fix: checkum CI script second try

---

.releaserc.yml

fix: checksum third try

---

.github/workflows/Deployment.yml

fix: ci xcode version needs to be updated

---

.github/workflows/Deployment.yml

ci: remove wrong matrix condition

---

apollo/build.gradle.kts
build.gradle.kts
secp256k1-kmp/build.gradle.kts

Only allow the publishing for:
- JVM
- Android
- KMP
Only for these modules:
- Apollo

build:  Disable publish to all but (JVM, Android, KMP)

---

README.md

fix: add documentation and release a new version

---

apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/securerandom/SecureRandom.kt
apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/utils/HelperMethods.kt
apollo/src/jsTest/kotlin/io/iohk/atala/prism/apollo/securerandom/JSSecureRandomTests.kt

Fix crypto is not defined
Fixes #135

fix: crypto is not defined

---

apollo/build.gradle.kts

update android compile sdk from 32 to 33

build: update android compile sdk from 32 to 33

---

build.gradle.kts

build: Update kover version

---

README.md
apollo/build.gradle.kts
build.gradle.kts

build(docs): Update the readme

---

.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
apollo/build.gradle.kts
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
iOSLibs/build.gradle.kts
secp256k1-kmp/build.gradle.kts

fix: upgrade gradle & libs

---

.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
.gitmodules
apollo/build.gradle.kts
apollo/src/androidInstrumentedTest/kotlin/io/iohk/atala/prism/apollo/derivation/EdHDKeyTest.kt
apollo/src/androidMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/androidMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/appleMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/appleMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/commonMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/commonMain/kotlin/org/hyperledger/identus/apollo/utils/ConvertEd25519.kt
apollo/src/commonMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdKeyPair.kt
apollo/src/commonMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/commonTest/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKeyTest.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/Curve25519Parser.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/external/Ed25519_Bip32.kt
apollo/src/jvmMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/jvmMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/nativeInterop/cinterop/ed25519_bip32_wrapper.def
apollo/webpack.config.d/polyfill.js
build.gradle.kts

Adding ed25519 derivation through submodule and wrapper code.

feat: ed25519 derivation

---

apollo/build.gradle.kts

Reverting changes preventing us from publishing to npm

revert build.gradle npmPublish

---

build.gradle.kts

Reverting PublishedMavenId to try fix release

fix: revert PublishedMavenId

---

apollo/build.gradle.kts

Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable. Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.

fix: task dependency

---

.github/workflows/pr-title-validation.yml

Add PR title validation to be in line with conventional commits.

ci: Validate PR title

---

.gitmodules
apollo/src/androidMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/appleMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/external/Ed25519_Bip32.kt
apollo/src/jvmMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDKey.kt

Just upgrading the library to fix the package for all platforms

fix: update usage of the bip32ed25519 wrapper.

---

.github/workflows/pr-title-validation.yml
.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml

Fix the current issue with CI failing.

ci: fix ci

---

.github/workflows/release.yml

fix: fix wrong variable names which should use _ not -

---

README.md
build.gradle.kts
gradle.properties
iOSLibs/IOHKAES/IOHKAES.podspec
iOSLibs/IOHKCryptoKit/IOHKCryptoKit.podspec
iOSLibs/IOHKRSA/IOHKRSA.podspec
iOSLibs/IOHKSecureRandomGeneration/IOHKSecureRandomGeneration.podspec
jajaj
package.json

This PR attempts to fix some wrong repositories in Apollo.

fix: wrong repository urls

---

.github/workflows/release.yml
commit
gradle.properties

Fix CI by swapping to use the right env variables with permission to push changes.

fix: adding identus CI

---

README.md

Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable. Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.

feat: almost empty commit to test the release

---

build.gradle.kts

Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable. Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.

fix: change oss publishing url according to the documentation
