hyperledger-identus/apollo

apollo/src/androidMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
apollo/src/appleMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
apollo/src/commonMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt
apollo/src/jvmMain/kotlin/io/iohk/atala/prism/apollo/hashing/PBKDF2SHA512.kt

Change PBKDF2SHA512 from class to Object

refactor: Change PBKDF2SHA512 from class to Object

---

apollo/build.gradle.kts

Enable documentation to be exported to the generated Swift/Obj-C code.

build: Enable documentation export to generated Swift/Obj-C code

---

apollo/build.gradle.kts
apollo/src/nativeInterop/cinterop/libsecp256k1.def
build.gradle.kts
secp256k1-kmp/build.gradle.kts

Remove Secp256k1-kmp module as dependency and use the module as source code only.

fix: The need to publish another module to use Apollo

---

apollo/build.gradle.kts

There is a bug on Apollo build, that is preventing clients from pushing apps to the App Store.
- [] My PR follows the [contribution guidelines](https://github.com/input-output-hk/atala-prism-apollo/blob/main/CONTRIBUTING.md) of this project
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have checked the PR title to follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/)

fix: current bug when trying to publish an app on app store with apollo inside

---

apollo/src/jvmMain/kotlin/io/iohk/atala/prism/apollo/secp256k1/Secp256k1Lib.kt
apollo/src/jvmTest/kotlin/io.iohk.atala.prism.apollo/utils/Secp256k1LibJVMTests.kt

Relates to [[ATL-6907]](https://input-output.atlassian.net/browse/ATL-6907) we are unlocking this functionality in Apollo to make sure that we can validate any kind of secp256k1 signature, from bc or bitcoin format.
[ATL-6907]: https://input-output.atlassian.net/browse/ATL-6907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Allow Apollo to verify der signatures from bc and bitcoin seamlessly #ATL-6905

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

- Code owners: define the actual codeowner as Ahmed Moussa and the content editor will be automatically added to any PR related to markdown files
- Pull request template: modify to be able to check / uncheck boxes without editing the comment

docs: update code owners and fix pull request template

---

.releaserc.yml

Fixes Apollo CI pipeline to just publish the npm package when a new release is triggered.

fix: npm package not being published automatically on CI pipeline.

---

apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/secp256k1/Secp256k1Lib.kt
apollo/src/jsTest/kotlin/io/iohk/atala/prism/apollo/utils/Secp256k1LibTestJS.kt

Adding a fix for JS signatures which result in     Invalid signature integer: negative.
Simply added a try catch and now we conditionally run the transcoding function as last resource.
All CommonMain and JSMain tests are working.
+ On top of this, have integrated the package manually in TS until I got that working :) 
we are good to go

fix:  Invalid signature integer: negative on JS platform

---

.github/workflows/pr-title-validation.yml
.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
CONTRIBUTING.md
README.md
apollo/build.gradle.kts

Under https://input-output.atlassian.net/browse/ATL-6475 and according to the replacement table, references to Atala were renamed to conform with brand position.
The changes are mostly to "readme" and other md files, as changes to the code require in-depth assessment of impact by an expert of this artifact.
In cases where the instruction referred to a variable name, this was rebranded both at the instruction document and the affected automation script.

fix: Removed references to Atala in docs and variables referred to by docs

---

.github/CODEOWNERS
.github/workflows/pr-title-validation.yml
.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
apollo/build.gradle.kts
build.gradle.kts

Replacing the tokens and npm namespace for apollo following the identus-docs repository started by @yshyn-iohk 
https://github.com/hyperledger/identus-docs/pull/111/files

fix: move to hyperledger and update ci tasks

---

.github/PULL_REQUEST_TEMPLATE.md
Package.swift
README.md
apollo/build.gradle.kts
build.gradle.kts
commit
iOSLibs/IOHKAES/IOHKAES.podspec
iOSLibs/IOHKCryptoKit/IOHKCryptoKit.podspec
iOSLibs/IOHKRSA/IOHKRSA.podspec
iOSLibs/IOHKSecureRandomGeneration/IOHKSecureRandomGeneration.podspec
jajaj
package.json

Moving to HL, simple changes pointing to the new repo.

fix: ci issues after moving to HL 

---

iOSLibs/IOHKAES/IOHKAES.podspec
iOSLibs/IOHKCryptoKit/IOHKCryptoKit.podspec
iOSLibs/IOHKRSA/IOHKRSA.podspec
iOSLibs/IOHKSecureRandomGeneration/IOHKSecureRandomGeneration.podspec
package.json

Fixing some wrong urls generated on a replace.

fix: fix wrong git repository url

---

gradle.properties

Increase version manually to 1.3.7 in Apollo to let the CI continue + release TS again.

fix: force bump to 1.3.7

---

gradle.properties

Forcing the CI task to release next version for (swift and kmm).
Everything is released using a single semantic-release config and because the previous builds didn't fully finish the only way to get out of the situation is by bumping the version directly and forcing the next increase.

fix: bump version for CI

---

.github/workflows/pull-request.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
build.gradle.kts

fix: Update to node20 actions

---

apollo/build.gradle.kts

Upgrading elliptic package rather than trashing it out with latest version which will solve the low severity vulnerabilities.

fix: upgrade elliptic dependency

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPrivateKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/KMMEdPublicKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/external/Ellipticjs.kt
apollo/src/jsTest/kotlin/org/hyperledger/identus/apollo/utils/KMMEdKeyPairTests.kt

After some investigation, we are returning a hex encoded buffer with the signature in JS which causes compatibility issues across SDK and we are also improving the test coverage for ed25519 by using the same values on all platforms we test

fix: make fixes to ed25519 sign method + improve tests

---

.github/workflows/pull-request.yml
apollo/build.gradle.kts

actions/upload-artifact and actions/download-artifact have been deprecated and need updated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

chore: update actions

---

apollo/build.gradle.kts

Replacing vulnerable elliptic package with latest updates, this is mainly used in the typescript SDK and we are having failed CI actions due to this.

fix: upgrade apollo to 6.6.1

---

apollo/src/androidMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKey.kt
apollo/src/appleMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKey.kt
apollo/src/commonMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKey.kt
apollo/src/commonTest/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKeyTest.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKey.kt
apollo/src/jsMain/kotlin/org/hyperledger/identus/apollo/utils/external/Ed25519_Bip32.kt
apollo/src/jvmMain/kotlin/org/hyperledger/identus/apollo/derivation/EdHDPubKey.kt

feat: add bip32 pub key derivation
